apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - ../../base/namespace.yaml
  - ../../base/postgres.yaml
  - ../../base/valkey.yaml
  - ../../base/rabbitmq.yaml
  - ../../base/keycloak.yaml
  - ../../base/keycloak-realm.yaml

commonLabels:
  environment: production
  component: datalayer

replicas:
  - name: postgres
    count: 1
  - name: valkey
    count: 1
  - name: rabbitmq
    count: 1
