apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: app
spec:
  template:
    spec:
      containers:
      - name: auth-service
        env:
        - name: KEYCLOAK_URL
          value: "http://auth.LOADBALANCER_IP.nip.io"
