apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: app
data:
  powerlifting-coach-realm.json: |
    {
      "realm": "powerlifting-coach",
      "enabled": true,
      "sslRequired": "none",
      "registrationAllowed": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "verifyEmail": true,
      "smtpServer": {
        "password": "${env.AZURE_EMAIL_SMTP_PASSWORD}",
        "starttls": "true",
        "auth": "true",
        "port": "587",
        "host": "${env.AZURE_EMAIL_SMTP_HOST}",
        "from": "${env.AZURE_EMAIL_FROM_EMAIL}",
        "fromDisplayName": "Coach Potato",
        "user": "${env.AZURE_EMAIL_SMTP_USERNAME}"
      },
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "User role"
          },
          {
            "name": "athlete",
            "description": "Athlete user type"
          },
          {
            "name": "coach",
            "description": "Coach user type"
          }
        ]
      },
      "identityProviders": [
        {
          "alias": "google",
          "providerId": "google",
          "enabled": true,
          "updateProfileFirstLoginMode": "on",
          "trustEmail": true,
          "storeToken": false,
          "addReadTokenRoleOnCreate": false,
          "authenticateByDefault": false,
          "linkOnly": false,
          "firstBrokerLoginFlowAlias": "first broker login",
          "config": {
            "clientId": "${env.GOOGLE_CLIENT_ID}",
            "clientSecret": "${env.GOOGLE_CLIENT_SECRET}",
            "hostedDomain": "",
            "useJwksUrl": "true"
          }
        }
      ],
      "identityProviderMappers": [
        {
          "name": "google-user-attribute-mapper",
          "identityProviderAlias": "google",
          "identityProviderMapper": "google-user-attribute-mapper",
          "config": {
            "syncMode": "INHERIT",
            "jsonField": "email",
            "userAttribute": "email"
          }
        }
      ],
      "clients": [
        {
          "clientId": "powerlifting-coach-app",
          "enabled": true,
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "redirectUris": ["*"],
          "webOrigins": ["*"],
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "user_type",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-attribute-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "user_type",
                "claim.name": "user_type",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ]
    }
